(()=>{'use strict';
const BASE='https://luizemsaopaulo.github.io/cantinho-do-petisco-v3/',DEL=BASE+'?v=14',RES=BASE+'restaurante.html?v=14';let deferredPrompt=null;const $=id=>document.getElementById(id);const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;const isiOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);const safariIOS=()=>isiOS()&&/safari/i.test(navigator.userAgent)&&!/crios|fxios|edgios/i.test(navigator.userAgent);
function toast(m,t='success'){const r=$('toastRegion');if(!r)return;const e=document.createElement('div');e.className=`toast ${t}`;e.textContent=m;r.appendChild(e);setTimeout(()=>e.remove(),2600)}
function refresh(){const b=$('installAdminPwa');if(b)b.classList.toggle('hidden',standalone()||(!deferredPrompt&&!safariIOS()))}
async function install(){if(safariIOS()){const d=$('adminIosInstallDialog');if(d&&!d.open)d.showModal();return}if(!deferredPrompt)return;deferredPrompt.prompt();const c=await deferredPrompt.userChoice.catch(()=>({outcome:'dismissed'}));if(c.outcome==='accepted')toast('Cantinho Admin instalado.');deferredPrompt=null;refresh()}
function share(mode){const delivery=mode==='delivery',url=delivery?DEL:RES,title=delivery?'🍽️ *Cantinho do Petisco*':'🍽️ *Cantinho do Petisco — Cardápio do Restaurante*',line=delivery?'Confira nosso cardápio e faça seu pedido:':'Confira nosso cardápio completo:';window.open(`https://wa.me/?text=${encodeURIComponent(`${title}\n${line}\n${url}`)}`,'_blank','noopener')}
async function copy(url){try{await navigator.clipboard.writeText(url);toast('Link copiado.')}catch{const t=document.createElement('textarea');t.value=url;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('Link copiado.')}}
function qr(mode){const delivery=mode==='delivery';$('qrDialogTitle').textContent=delivery?'QR Code — Delivery':'QR Code — Restaurante';$('qrDialogImage').src=delivery?'assets/qr-delivery-v14.png':'assets/qr-restaurante-v14.png';$('qrDialogLink').textContent=delivery?DEL:RES;const d=$('qrDialog');if(d&&!d.open)d.showModal()}
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=14',{scope:'./'}).catch(()=>{}));addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;refresh()});addEventListener('appinstalled',()=>{deferredPrompt=null;refresh()});
document.addEventListener('DOMContentLoaded',()=>{refresh();$('installAdminPwa')?.addEventListener('click',install);$('closeAdminIosInstall')?.addEventListener('click',()=>$('adminIosInstallDialog')?.close());$('openDeliveryQuick')?.addEventListener('click',()=>window.open(DEL,'_blank','noopener'));$('openRestaurantQuick')?.addEventListener('click',()=>window.open(RES,'_blank','noopener'));$('shareDeliveryWhatsApp')?.addEventListener('click',()=>share('delivery'));$('shareRestaurantWhatsApp')?.addEventListener('click',()=>share('restaurante'));$('copyDeliveryLink')?.addEventListener('click',()=>copy(DEL));$('copyRestaurantLink')?.addEventListener('click',()=>copy(RES));$('qrDeliveryBtn')?.addEventListener('click',()=>qr('delivery'));$('qrRestaurantBtn')?.addEventListener('click',()=>qr('restaurante'));$('closeQrDialog')?.addEventListener('click',()=>$('qrDialog')?.close())});
})();
